
INSERT INTO STUDENT (name, age) VALUES ('Bob', 24);
INSERT INTO STUDENT (name, age) VALUES ('Sara', 25);
INSERT INTO STUDENT (name, age) VALUES ('Ellie', 26);
INSERT INTO STUDENT (name, age) VALUES ('Tommy', 23);


INSERT INTO COURSE (UUID, DESCRIPTION) VALUES ('a7da2470-c211-11ef-8d69-a002a502e878', 'English');
INSERT INTO COURSE (UUID, DESCRIPTION) VALUES ('a7db1b80-c211-11ef-8d69-a002a502e878', 'Maths');
INSERT INTO COURSE (UUID, DESCRIPTION) VALUES ('a7dc436d-c211-11ef-8d69-a002a502e878', 'Science');


INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (1, 1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (1, 2);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (1, 3);

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (2, 1);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (2, 2);

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (3, 3);

-- INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (4, 1);

-- INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (4, 2);