
DROP TABLE IF EXISTS STUDENT_COURSE CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;
DROP TABLE IF EXISTS COURSE CASCADE;

CREATE TABLE STUDENT (
	STUDENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	AGE INT NOT NULL
);

CREATE TABLE COURSE (
	COURSE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UUID VARCHAR(255) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL
);

CREATE TABLE STUDENT_COURSE (
	STUDENT_ID INT NOT NULL,
	COURSE_ID INT NOT NULL,
	ENROLLED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
